---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-web
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: hello-world-web-mapping
      prefix: /hello
      service: hello-world-web
      host: test.example.com
spec:
  selector:
    app: hello-world-web
  ports:
    - port: 80
      targetPort: http-api
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-world-web
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world-web
    spec:
      containers:
      - name: hello-world-web
        image: tutum/hello-world:latest
        imagePullPolicy: Always
        ports:
        - name: http-api
          containerPort: 80